"""initial migration

Revision ID: 772360816642
Revises: c835a91498be
Create Date: 2025-12-04 15:08:59.886572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772360816642'
down_revision = 'c835a91498be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_structure_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('data_structure_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_structure_fields', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('data_structure_templates')
    # ### end Alembic commands ###
