"""initial migration

Revision ID: dab27c23c173
Revises: 772360816642
Create Date: 2025-12-05 16:00:30.706352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab27c23c173'
down_revision = '772360816642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('source_column', sa.String(length=255), nullable=False),
    sa.Column('target_field', sa.String(length=255), nullable=False),
    sa.Column('transformation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['data_structure_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_structure_fields', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'data_structure_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_structure_fields', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('template_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)

    op.drop_table('field_mappings')
    # ### end Alembic commands ###
